<?php if(Mage::getStoreConfig('infinite_scroll/infinite_scroll_settings/scroll_loader_active')): ?>
<script type="text/javascript">
		var ias  = jQuery.ias({
		  container 	: ".wrapper-categoria",
		  		// Enter the selector of the element containing
		  		// your items that you want to paginate.
		 
		  item		: ".prod",
				// Enter the selector of the element that each
				// item has. Make sure the elements are inside
				// the container element.
		 
		  pagination	: ".pages",
				// Enter the selector of the element that contains
				// your regular pagination links, like next,
				// previous and the page numbers. This element
				// will be hidden when IAS loads.
		 
		  next		: ".pages a.next",
				// Enter the selector of the link element that
				// links to the next page. The href attribute
				// of this element will be used to get the items
				// from the next page.
		 
		  loader	: "<img src='https://www.nutrii.com.br/media/images/loading-nutrii.gif' style='margin-left:48%'/>"
				// Enter the url to the loader image. This image
				// will be displayed when the next page with items
				// is loaded via AJAX.
		});
		
		ias.on('rendered', function(items) {
		    $j(".list-qtd span.less").on("click", function() {
	            var qtd_current = parseInt($j(this).parents(".list-qtd").find("input").val());
	            return qtd_current--, 0 >= qtd_current && (qtd_current = 1), qtd_current > 9 || (qtd_current = qtd_current),$j(this).parents(".list-qtd").find("input").val(qtd_current), !1
	        });
	        $j(".list-qtd span.more").on("click", function() {
	            var qtd_current = parseInt($j(this).parents(".list-qtd").find("input").val());
	            return qtd_current++, qtd_current > 9 || (qtd_current = qtd_current), $j(this).parents(".list-qtd").find("input").val(qtd_current), !1
	        });
		});
				
		ias.extension(new IASSpinnerExtension({
			src: 'https://www.nutrii.com.br/media/images/loading-nutrii.gif',
		}));
		ias.extension(new IASTriggerExtension({offset: 1, text: 'Veja mais Produtos'})); 
		
</script>
<?php endif; ?>