<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
	<li>		
		<div class="divPagamentoSuperPayBoleto">
			<?php 
				$_banks = split(",",Mage::getStoreConfig('payment/superpay_banco/banks'));
				Mage::log('## Form Banks = '.print_r($_banks,true),null,'ernet.log');					
				$primeiraExecucao = true;
				foreach ($_banks as $_typeCode){ 
					$_typeName = Mage::getModel('superpay/superpaybanco')->getBanks($_typeCode);
					Mage::log('## Retrieved Bank Type = '.$_typeName,null,'ernet.log');
			?>																					
					<?php if ($primeiraExecucao == false) { ?>
						<input type="radio" id="<?php echo $_code ?>_bank_type" class="validate-one-required inputRadioPagamentoSuperPayBoleto" name="payment[service]" value="<?php echo $_typeCode ?>">
					<?php } else {
						$primeiraExecucao = false; ?>
						<input type="radio" id="<?php echo $_code ?>_bank_type" checked class="validate-one-required inputRadioPagamentoSuperPayBoleto" name="payment[service]" value="<?php echo $_typeCode ?>">
					<?php } ?>
					
					<label for="<?php echo $_code ?>_bank_type" class="labelPagamentoSuperPayBoleto">						
							<?php 							
								if (Mage::getStoreConfig('payment/superpay_banco/showImagePaymentMethod') == true) {														
							?>
								<div class="divBandeiraPagamentoSuperPayBoleto">
								<?php							
									if ($_typeCode == 120 or $_typeCode == 129 or $_typeCode == 130 or $_typeCode == 139 or $_typeCode == 40 or $_typeCode == 80 or $_typeCode == 90 or $_typeCode == 3){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/methods-visa.gif ">';
									}else if ($_typeCode == 121 or $_typeCode == 131 or $_typeCode == 81 or $_typeCode == 91 or $_typeCode == 6){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/methods-master.gif ">';
									}else if ($_typeCode == 122 or $_typeCode == 132 or $_typeCode == 10 or $_typeCode == 11 or $_typeCode == 12){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/methods-amex.gif ">';
									}else if ($_typeCode == 123 or $_typeCode == 133 or $_typeCode == 63 or $_typeCode == 73){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/methods-elo.gif ">';	
									}else if ($_typeCode == 124 or $_typeCode == 134 or $_typeCode == 82 or $_typeCode == 92 or $_typeCode == 9){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/methods-diners.gif ">';
									}else if ($_typeCode == 125 or $_typeCode == 135){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/methods-discover.gif ">';
									}else if ($_typeCode == 126 or $_typeCode == 136){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/aura.png ">';
									}else if ($_typeCode == 127 or $_typeCode == 137 or $_typeCode == 15){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/methods-jcb.gif ">';
									}else if ($_typeCode == 93 or $_typeCode == 13){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/methods-hypercard.png ">';
									}else if ($_typeCode == 14){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/sorocred.png ">';
									}else if ($_typeCode == 16 or $_typeCode == 17 or $_typeCode == 29 or $_typeCode == 31){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/itau.png">';
									}else if ($_typeCode == 18 or $_typeCode == 19 or $_typeCode == 30 or $_typeCode == 140){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/bradesco.png">';
									}else if ($_typeCode == 20 or $_typeCode == 33){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/transferencia_real.png">';
									}else if ($_typeCode == 21 or $_typeCode == 28){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/transferencia_bb.jpg">';
									}else if ($_typeCode == 22 or $_typeCode == 100 or $_typeCode == 32){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/hsbc.jpg">';
									}else if ($_typeCode == 23 or $_typeCode == 24 or $_typeCode == 25 or $_typeCode == 26){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/banrisul.png">';
									}else if ($_typeCode == 27){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/oipaggo.png">';
									}else if ($_typeCode == 34){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/caixa.jpg">';
									}else if ($_typeCode == 35){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/moip.png">';
									}else if ($_typeCode == 36){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/mercadopago.png">';
									}else if ($_typeCode == 37){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/pagamentodigital.png">';
									}else if ($_typeCode == 38){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/pagseguro.png">';
									}else if ($_typeCode == 110 or $_typeCode == 111){
										echo '<img src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/paypal.png">';
									} else {				
										echo '<img id="'.$_typeName.'" src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'superpay_superpay/img_cartao_default.png ">';
									}
								?>
								</div>
							<?php	
							}
							?>						
						<div class="divTextoBandeiraPagamentoSuperPayBoleto">
							<?php
								if (Mage::getStoreConfig('payment/superpay_banco/showLabelPaymentMethod') == true) {								
									echo $_typeName;								
								}
							?>
						</div>
					</label>					
		<?php } ?>		
		</div>
	</li>		
</ul>
<?php Mage::log('## End BOLETO Form output.',null,'ernet.log'); ?>

<style media="screen" type="text/css">	
	.divPagamentoSuperPayBoleto { float:left; clear:none; }
	.labelPagamentoSuperPayBoleto { float:left; clear:none; display:block; padding: 2px 1em 10px 0; }
	.inputRadioPagamentoSuperPayBoleto { float:left; clear:none; margin: 30px 15px 0 2px; }
	.divBandeiraPagamentoSuperPayBoleto { width: 80px ; height: 80px; overflow: hidden; }
	.divTextoBandeiraPagamentoSuperPayBoleto { width: 80px ; word-wrap:break-word ; }
</style>
