<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<?php $_collectionSize = count($_products->getItems()) ?>

<div id="colunas9">&nbsp;</div>
<div id="colunas9" class="home-info">
	<h3 class="titleBox titleBox2"><span><strong>MAIS VENDIDOS</strong></span></h3>
</div>

<?php $i=1; foreach ($_products->getItems() as $_product): ?>
    <div id="colunas3" class=" prod <?php if($i%3==0 or $i==$_collectionSize){echo 'last';} ?>">
        <div class="nova-h">  
            <div class="tag-label">
				<?php 
				$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
				$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();
				$now = date("Y-m-d");
				if($newFromDate < $now && $newToDate >= $now): ?>
					<p class="novo">novidade</p>
				<?php endif; ?>

				<?php
		    		$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
		    		$specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
		    		$specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
		    		$today =  time(); 
		    		if ($specialprice):
		        		if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)): ?>
						<p class="oferta">promo&ccedil;&atilde;o</p>
					<?php  
		        		endif;
		    		endif; 
	    		?>
            </div>
    		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="img-prod" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(263); ?>" width="263" height="263" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
       		<div id="info-prod">
				<a class="fs-14 txt d-b" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><h2><?php echo $this->htmlEscape($_product->getName()) ?></h2></a>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<div class="bt-nova">
					<a href="<?php echo $_product->getProductUrl() ?>" title="Comprar">Comprar</a>
				</div>
			</div>
        </div>
    </div>
<?php $i++; endforeach; $kol = $_collectionSize; ?>

<?php endif; ?>