<?php
/** Product list template
 * @see Mage_Catalog_Block_Product_List
 **/
?>

<?php $this->_reviewsHelperBlock = $this->getLayout()->createBlock('review/helper');?>
<?php $_productCollection=$this->getLoadedProductCollection(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>

<?php if(!$_productCollection->count()): ?>
    <div id="colunas12">
        <p class="note-msg proxima-nova"><?php echo $this->__('There are no products matching the selection.') ?></p>
    </div>
<?php else: ?>

    <div class="wrapper-categoria">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = 4; ?>

        <?php $i=0; foreach ($_productCollection as $_product): $reqProductId = $_product->getId(); ?>

            <?php if ($i++%$_columnCount==0): ?>
            <?php endif ?>

            <div id="colunas3" class="prod <?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="nova-h">
                    <div class="tag-label">
                        <?php if($_product->isSaleable()): ?>
                        <?php else: ?>
                            <p class="novo">esgotado</p>
                        <?php endif; ?>

                        <?php
                        $newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
                        $newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();
                        $now = date("Y-m-d");
                        if($newFromDate < $now && $newToDate >= $now): ?>
                            <p class="kepler-bold-italic novo">novidade</p>
                        <?php endif; ?>

                        <?php
                        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
                        $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                        $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                        $today =  time();
                        if ($specialprice):
                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)): ?>
                                <p class="kepler-bold-italic oferta">promo&ccedil;&atilde;o</p>
                            <?php
                            endif;
                        endif;
                        ?>
                    </div>
                    <a href="<?php echo $_product->getProductUrl()?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image loading">
                        <img class="img-prod b-lazy" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(263)->setQuality(100); ?>" width="263" height="263" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                    </a>

                    <div id="info-prod">
                        <a class="fs-19 txt d-b bold" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2></a>
                        <div class="mob">
                            <div class="list-rating"><?php echo $this->_reviewsHelperBlock->getSummaryHtml($_product, false, false); ?></div>

                            <?php
                            /* Desconto em uma vez no cartão (5% de desconto) */

                            $desconto = 5;
                            $preco = $_product->getMinimalPrice();
                            $precoComDesconto = $preco - ($preco * $desconto / 100);

                            $msgDescCartao   = "<p class='msg-desconto-cartao'>";
                            $msgDescCartao  .=     "<span class='medium'>em 1x no cartão de crédito por:</span>";
                            $msgDescCartao  .=     "<span class='display-preco-com-desconto bold'>R$ ".number_format($precoComDesconto, 2, ',', '')."</span>";
                            $msgDescCartao  .= "</p>";

                            echo $msgDescCartao;
                            ?>

                            <?php if(!$_product->isGrouped()): ?>
                            <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                                <div class="list-qtd">
                                    <span class="less">-</span>
                                    <input class="op-i" type="text" name="qty" id="qty" maxlength="5" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" aria-label="Quantidade"/>
                                    <span class="more">+</span>
                                </div>
                                <?php endif; ?>
                                <div class="bt-nova">
                                    <a href="javascript:void(0)" title="Comprar" onclick="jQuery(this).parents('form').submit(); return false">Comprar</a>
                                </div>
                                <input type="submit" class="hide" />
                            </form>

                        </div>
                    </div>
                </div>
                <script type="application/ld+json">
                {
                    "@context": "https://www.schema.org",
                    "@type": "product",
                    "name": "<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>",
                    "image": "<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(263); ?>",
                    "url": "<?php echo $_product->getProductUrl() ?>",
                    "offers": {
                        "@type": "Offer",
                        "priceCurrency": "BRL",
                        "price": <?php echo $_product->getFinalPrice(); ?>,
                        "itemCondition": "https://schema.org/NewCondition",
                        "availability": "https://schema.org/InStock",
                        "seller": {
                            "@type": "Organization"
                        }
                    }
                }
            </script>

            </div>
            <?php if ($i == 4) break; ?>
        <?php endforeach ?>


    </div>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<?php endif; ?>
