<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>

<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
    <input type="hidden" name="related_product" id="related-products-field" value="" />

    <div id="colunas6">
      <?php echo $this->getChildHtml('media') ?>
    </div>

    <div id="colunas6" class="product-info">
    	<h1 class="bold cor fs-20 d-b"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
        <br />
        <p class="fs-14">C&oacute;d. do Produto: <?php echo $_product->getSku() ?></p>

    	<?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <div id="product-att">
            	<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            </div>
        <?php endif;?>
        
        <div id="colunas3" class="m-auto">
        	<p class="fs-20 bold"><?php echo $this->getPriceHtml($_product, true) ?></p>
    	    <p class="fs-20 bold cor">
    		<?php
    			$Preco = $_product->getFinalPrice();
    			if($Preco >= 1 and $Preco <= 39.90 ){ 
    				$Parcelamento = 1;
    				}else if($Preco >= 79.90 and $Preco <= 119.80){ 
    				$Parcelamento = 2;
    				}else if($Preco >= 119.90 and $Preco <= 159.60){
    				$Parcelamento = 3; 
    				}else if($Preco >= 159.70 and $Preco <= 199.50){
    				$Parcelamento = 4; 
    				}else if($Preco >= 199.60 and $Preco <= 239.40){
    				$Parcelamento = 5; 
    				}else if($Preco >= 239.50 and $Preco <= 279.60){
    				$Parcelamento = 6; 
    				}else if($Preco >= 279.70 and $Preco <= 319.20){
    				$Parcelamento = 7; 
    				}else if($Preco >= 319.30 and $Preco <= 359.10){
    				$Parcelamento = 8; 
    				}else if($Preco >= 359.20 and $Preco <= 398.90){
    				$Parcelamento = 9; 
    				}else if($Preco >= 399){
    				$Parcelamento = 10; 
    			}
    			$Resultado = $Preco/ $Parcelamento;
    			echo $Parcelamento . 'x</strong> de <strong>R$'.number_format($Resultado, 2, ',', '').'</strong> sem juros.';?>
            </p>
        </div>
        
        <div id="product-price" class="opacity-1-5 trans">
    	  <?php if($_product->isSaleable()): ?>
    	  <p class="fs-14 d-b txt bold">Em estoque</p>
    	  <input type="submit" value="Comprar &raquo;" class="bt-buy bt cor-sec d-b fs-20 radius bold" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
          <?php else: ?>
    	  <p class="fs-14 d-b txt bold">Produto Esgotado</p>
    	  <input type="submit" disabled="disabled" value="Comprar &raquo;" class="bt-buy no-bt cor-sec d-b fs-20 radius bold">
          <?php endif; ?>  
        </div>

        <div id="product-att">
        	<ul class="social-share">
    			<li>
    				<div class="fb-like" data-href="http://www.facebook.com/mucciestudio" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true"></div>
    			</li>
    			<li>
    			    <!-- Place this tag in your head or just before your close body tag. -->
    				<script type="text/javascript" src="https://apis.google.com/js/plusone.js">
    			  		{lang: 'pt-BR'}
    				</script>
    			     <!-- Place this tag where you want the share button to render. -->
    				<div class="g-plus" data-action="share" data-annotation="bubble" data-href="localhost"></div>
    			</li>
    			<li>
    				<a href="//pinterest.com/pin/create/button/" data-pin-do="buttonBookmark" ><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a>
    			</li>
    			<li>
    				<a class='twitter-share-button' data-count='horizontal' expr:data-url='data:post.url' data-via='SEU_TWITTER' expr:data-text='data:post.title' href='http://twitter.com/share'>Twittar</a>
                    <script src='http://platform.twitter.com/widgets.js' type='text/javascript'></script>
    			</li>
    			<li>
    				<a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><img src="<?php echo $this->getSkinUrl('images/mail.jpg'); ?>" width="28" height="19" /</a>
    			</li>
    		</ul>
        </div>
    </div>

    <div id="colunas12">
        <?php echo $this->getChildHtml('upsell_products') ?>
    	<?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
</script>

</div>
</div>

<div id="full" class="no-home">
	<div id="wrapper">