<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>

<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<?php //echo $this->getChildHtml('product_type_data') ?>

<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<?php $_storeId = Mage::app()->getStore()->getId(); ?>
<?php $_isActive = Mage::getStoreConfig('outofstocksubscription/mail/active', $_storeId); ?>

<?php if(!$_product->isSaleable() && $_isActive): ?>
    <?php $_url = $this->getUrl('outofstocksubscription') ?>
<?php else: ?>
    <?php $_url = $this->getSubmitUrl($_product); ?>
<?php endif; ?>

<form action="<?php echo $_url ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

    <?php echo $this->getBlockHtml('formkey') ?>

    <div class="no-display">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
    </div>

    <div id="colunas12"></div>

    <div id="colunas6">
        <?php echo $this->getChildHtml('media') ?>
    </div>

    <div id="<?php echo $_product->getUrlPath(); ?>">

        <div id="colunas6" class="product-info no-bottom">

            <h1 class="bold cor fs-24 d-b tt-u ta-c"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

            <?php if($_product->getData('subtitulo')): ?>
                <h2 class="medium cor fs-20 d-b ta-c"><?php echo $_product->getData('subtitulo'); ?></h2>
            <?php endif; ?>

            <h3 class="fs-16 ta-c medium categories_product">
                <?php
                $catIds = $_product->getCategoryIds();
                $texto = "";
                $catCollection = Mage::getResourceModel('catalog/category_collection')
                    ->addAttributeToSelect('*')
                    ->addAttributeToFilter('entity_id', $catIds)
                    ->addIsActiveFilter();

                foreach($catCollection as $cat){
                    if( $cat->getName() != "Default Category" && $cat->getName() != "BLACK FRIDAY"){
                        $texto .= "<a href=" . $cat->getUrl() .">" . $cat->getName() . "</a>";
                    }
                };
                echo "Categorias: " . $texto;
                ?>
            </h3>

            <p class="fs-14 cod ta-c">C&oacute;d. do Produto: <?php echo $_product->getSku() ?></p>

            <br /><div class="h-r f-l d-b"></div><br />

            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
            <?php echo $this->getChildHtml('alert_urls') ?>

            <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

            <?php
            $newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
            $newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();
            $now = date("Y-m-d");
            ?>

            <?php if($newFromDate < $now && $newToDate >= $now): ?>
                <p class="novo">novidade</p>
            <?php endif; ?>

            <div class="h-r f-l d-b"></div><br />

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>

                <div class="bundle-container">
                    <h2 class="cor bold fs-16">Itens do pacote</h2>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                </div>

            <?php endif;?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?><br />
                <div class="h-r f-l d-b"></div><br />
            <?php endif;?>

        </div>
    </div>

    <div id="colunas6" class="product-info no-bottom grid-desconto-cartao">

        <div class="left-all-prices">

            <div class="content-prices">


                <?php
                /* Desconto em uma vez no cartão (5% de desconto) */
                $desconto = 5;

                if ($_product->isSaleable() && $this->hasOptions()){

                    $preco = $this->getPriceHtml($_product);
                    $preco = strip_tags($preco);
                    $preco = str_replace("R$", "", $preco);
                    $preco = str_replace(",", ".", $preco);
                    $preco = (float) $preco;
                } else {

                    $preco = $_product->getFinalPrice();
                }
                $precoComDesconto = $preco - ($preco * $desconto / 100);

                $msgDescCartao   = "<p class=original-price medium'>";
                $msgDescCartao  .=   "<span class=preco'>R$ ".number_format($preco, 2, ',', '')."</span>";
                $msgDescCartao  .=   "<span> (5% de desconto)</span>";
                $msgDescCartao  .= "</p>";
                $msgDescCartao  .= "<p class='msg-desconto-cartao-produto'>";
                $msgDescCartao  .=     "<span class='display-preco-com-desconto bold'>R$ ".number_format($precoComDesconto, 2, ',', '')."</span>";
                $msgDescCartao  .=     "<span class='medium'>em 1x no cartão de crédito </span>";
                $msgDescCartao  .= "</p>";

                echo $msgDescCartao;
                ?>

                <?php $precoTotal = $preco; ?>

                <div class="mob">
                    <div class="bg-price ico-boleto medium">
                        <?php echo "R$ ".number_format($precoTotal, 2, ',', ''); ?> no boleto bancário ou transferência bancária
                    </div>

                    <?php if($precoTotal > 39.99): ?>

                        <div class="bg-price ico-cartao medium">
                            <?php

                            if($precoTotal >= 40 and $precoTotal <= 59.99){
                                $parcelas = 2;
                                $valorParcelado = $precoTotal / $parcelas;
                                echo 'R$ '.number_format($precoTotal, 2, ',', '').' em at&eacute; '. $parcelas .'x de R$'.number_format($valorParcelado, 2, ',', '').' sem juros no cart&atilde;o de cr&eacute;dito';
                            }
                            else if($precoTotal >= 60 and $precoTotal <= 79.99){
                                $parcelas = 3;
                                $valorParcelado = $precoTotal / $parcelas;
                                echo 'R$ '.number_format($precoTotal, 2, ',', '').' em at&eacute; '. $parcelas .'x de R$'.number_format($valorParcelado, 2, ',', '').' sem juros no cart&atilde;o de cr&eacute;dito';
                            }
                            else if($precoTotal >= 80 and $precoTotal <= 99.99){
                                $parcelas = 4;
                                $valorParcelado = $precoTotal / $parcelas;
                                echo 'R$ '.number_format($precoTotal, 2, ',', '').' em at&eacute; '. $parcelas .'x de R$'.number_format($valorParcelado, 2, ',', '').' sem juros no cart&atilde;o de cr&eacute;dito';
                            }
                            else if($precoTotal >= 100 and $precoTotal <= 119.99){
                                $parcelas = 5;
                                $valorParcelado = $precoTotal / $parcelas;
                                echo 'R$ '.number_format($precoTotal, 2, ',', '').' em at&eacute; '. $parcelas .'x de R$'.number_format($valorParcelado, 2, ',', '').' sem juros no cart&atilde;o de cr&eacute;dito';
                            }
                            else if($precoTotal >= 120){
                                $parcelas = 6;
                                $valorParcelado = $precoTotal / $parcelas;
                                echo 'R$ '.number_format($precoTotal, 2, ',', '').' em at&eacute; '. $parcelas .'x de R$'.number_format($valorParcelado, 2, ',', '').' sem juros no cart&atilde;o de cr&eacute;dito';
                            }
                            ?>
                        </div>

                    <?php endif;?>
                </div>

            </div>
        </div>

        <?php if($_product->isSaleable() && $_product->getTypeId() !== 'bundle'): ?>
            <div class="right-btn-and-qty">

                <div class="qty-content">
                    <span class="label-quantidade medium fs-14">Quantidade</span>
                    <div class="list-qtd">
                        <span class="less">-</span>
                        <input style="width:48px !important;text-align:center;margin:0px;" class="op-i" type="text" name="qty" id="qty" maxlength="6" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" />
                        <span class="more">+</span>
                    </div>
                </div>

                <div class="btn-content">
                    <input type="submit" value="COMPRAR" class="bt-buy-nova cor-sec d-b fs-20 radius bold validation-passed" onclick="productAddToCartForm.submit(this); return false;">
                </div>
            </div>
        <?php endif; ?>


        <?php if($_product->isSaleable() && $_product->getTypeId() === 'bundle'): ?>

            <div class="right-btn-and-qty">

                <div class="buy-bundle" style="display: none;">
                    <div class="qty-content">
                        <span class="label-quantidade medium fs-14">Quantidade</span>
                        <div class="list-qtd">
                            <span class="less">-</span>
                            <input style="width:48px !important;text-align:center;margin:0px;" class="op-i" type="text" name="qty" id="qty" maxlength="6" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" />
                            <span class="more">+</span>
                        </div>
                    </div>

                    <div class="btn-content">
                        <input type="submit" value="COMPRAR" class="bt-buy-nova btn-cart cor-sec d-b fs-20 radius bold validation-passed" onclick="productAddToCartForm.submit(this); return false;">
                    </div>
                </div>

                <div class="indisponible-bundle" style="display: none;">
                    <img class="prod-esg" src="<?php echo $this->getUrl('') ?>skin/frontend/default/adaptive-shop/images/produto-indisponivel.svg" alt="Produto Esgotado" width="250" />
                </div>

            </div>
        <?php endif; ?>

    </div>

    <div id="colunas6" class="product-info no-bottom ta-c">

        <div id="product-price">
            <br />

            <?php if(!$_product->isSaleable()): ?>

                <img class="prod-esg" src="<?php echo $this->getUrl('') ?>skin/frontend/default/adaptive-shop/images/ProdutoEsgotado-2x.png" alt="Produto Esgotado" width="250" />

                <?php if(!$_product->isSaleable() && $_isActive): ?>

                    <div class="out_of_stock_notification">
                        <h3 class="bold fs-16"><?php echo $this->__('Product Out of Stock Subscription') ?></h3>
                        <div class="form_out_of_stock">
                            <input type="text" id="subscription_email" name="subscription_email" value="" placeholder="email" class="input-text d-b op-i txt fs-14 required-entry validate-email op-i" />
                            <button onclick="productAddToCartForm.submit();" class="button btn-cart" type="button"><?php echo $this->__('Subscribe') ?></button>
                        </div>
                    </div>

                <?php endif; ?>

            <?php endif; ?>
        </div>

        <br />

        <div class="h-r f-l d-b"></div>

        <br />
    </div>

    <div id="colunas6" class="product-info no-bottom ta-c">
        <?php echo $this->getChildHtml('related') ?>
    </div>

    <div id="colunas12"></div>

    <div class="description-new-prod">
        <?php echo $_product->getDescription(); ?>
    </div>

</form>

<div id="anchor-c" class="f-l d-ib">&nbsp;</div>
<?php echo $this->getChildHtml('reviews') ?>

<div id="colunas12" class="product-info">
    <?php echo $this->getChildHtml('upsell_products') ?>
</div>

<script type="text/javascript">
    //<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }
            var e = null;
            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]>
</script>

</div>
</div>

<script>

    var msgSuccess = "";

    <?php if ($_url == $this->getUrl('outofstocksubscription')): ?>
    msgSuccess = "Avisaremos assim que o seu produto, estiver disponível!";
    <?php endif ?>

    jQuery("body.catalog-product-view #review-form button").click(function(){
        msgSuccess = "Seu comentário foi enviado com sucesso!";
        localStorage.setItem("message", msgSuccess);
        localStorage.setItem("tipo", "success");
    });

    jQuery("body.catalog-product-view .btn-cart").click(function(){

        localStorage.setItem("message", msgSuccess);
    });

</script>

<?php if( $_product->getTypeId() === 'bundle'): ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<script>
    window.addEventListener('load', function(){

        msgSuccess = "Quantidade selecionada indisponível.";
        localStorage.setItem("tipo", "error");

        var elem = document.querySelectorAll('.bundle_availability');
        var displayWarning;

        for (var i = 0 ; i < elem.length ; i++ ){

            if(elem[i].value == "indisponivel"){

                displayWarning = true;
                break;
            } else {

                displayWarning = false;
            };
        }

        if(displayWarning == true){

            document.querySelector('.indisponible-bundle').show();
        } else{

            document.querySelector('.buy-bundle').show();
        }

    });
</script>
<?php endif; ?>

<div id="full" class="no-home">
    <div id="wrapper">