<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>

<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).' style="max-width:100%;height:auto"/></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>

<?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
    <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
<?php endif; ?>

<p class="fs-14"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></p>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
	<div id="colunas9" class="fs-16 txt no-bottom">
		<h1 class="fs-24 cor bold"><?php echo $_category->getName(); ?></h1>
	</div>
	<div id="colunas9" class="fs-16 txt descricao-cat">
	   <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
	</div>
<?php endif; ?>