<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div id="colunas9">
    <h2 class="title_account ico_meus_enderecos">Meus Endereços</h2>
    <br />
    <button type="button" title="<?php echo $this->__('Add New Address') ?>" class="button bt radius cor-sec tt-u fs-14 bold td-n button_account" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><?php echo $this->__('Add New Address') ?></button>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

        <div id="colunas4">
        <ol>
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <li class="item account_info">
<!--                 <h3 class="account_interno"><?php echo $this->__('Default Billing Address') ?></h3> -->
                 <p class="txt fs-14"><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></p>
                <br>
                <a class="btn_interno_account trans ico_editar_account" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>">Alterar Endereço</a>
           </li>
           <br />
        <?php else: ?>
            <li class="item account_info">
                <h3 class="account_interno"><?php echo $this->__('Default Billing Address') ?></h3>
                <p class="txt fs-14"><?php echo $this->__('You have no default billing address in your address book.') ?></p>
            </li>
            <br />
        <?php endif ?>
        </div>
		<div id="colunas4">
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <li class="item account_info">
<!--                 <h3 class="account_interno"><?php echo $this->__('Default Shipping Address') ?></h3> -->
                <p class="txt fs-14"><?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?></p>
                <br>
                <a class="btn_interno_account trans ico_editar_account" href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>">Alterar Endereço</a>
            </li>
            <br />
        <?php else: ?>
            <li class="item empty account_info">
                <h3 class="txt fs-14 bold"><?php echo $this->__('Default Shipping Address') ?></h3>
                <p class="txt fs-14"><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            </li>
            <br />
        <?php endif ?>
		</div>
        </ol>
		<div id="colunas9">
		        <h2 class="txt fs-14 bold account_endereco_title"><?php echo $this->__('Additional Address Entries') ?></h2>
		        <ol>
		        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
		            <?php foreach($_pAddsses as $_address): ?>
		            <li class="item account_info">
		                <p class="txt fs-14"><?php echo $this->getAddressHtml($_address) ?></p>
		                <a class="cor fs-12" href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove cor fs-12" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a>
		            </li>
		            <?php endforeach; ?>
		        <?php else: ?>
		            <li class="item empty account_info">
		                <p class="txt fs-14"><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
		            </li>
		        <?php endif ?>
		        </ol>
		</div>


<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
