<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
<title>
<?php
	if (Mage::registry('current_product')) {
		$cat_id = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
		$category = Mage::getModel('catalog/category')->load($cat_id);
		echo $this->getTitle() ." | ". $category->getName();
	} else {
		echo $this->getTitle();
	}
?>
</title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />

<?php
	/**
	 * Open Graph Protocol for Facebook and SEO START
	 */
?>
<?php if(Mage::registry('current_product')): ?>
	<?php $product = Mage::registry('current_product'); ?>
	<meta property="og:title" content="<?php echo ($product->getName()); ?>" />
	<meta property="og:type" content="product" />
	<meta property="og:image" content="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(200,200);?>" />
	<meta property="og:url" content="<?php echo Mage::registry('product')->getProductUrl(); ?>" />
	<meta property="og:description" content="<?php echo strip_tags(($product->getShortDescription())); ?>" />
	<meta property="og:site_name" content="Nova Nutrii" />
	<meta property="og:price:amount" content="<?php echo Mage::registry('product')->getFinalPrice() ?>" />
	<meta property="og:price:currency" content="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>" />
<?php elseif(Mage::registry('current_category')): ?>
	<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
	<meta property="og:type" content="product.group" />
	<meta property="og:url" content="https://www.nutrii.com.br/" />
	<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
	<meta property="og:site_name" content="Nova Nutrii" />
<?php elseif((Mage::getSingleton('cms/page')->getIdentifier() == 'home' &&
	Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms')) : ?>
	<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://www.nutrii.com.br/" />
	<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
	<meta property="og:site_name" content="Nova Nutrii" />
<?php else: ?>
	<meta property="og:title" content="<?php echo $this->getTitle() ?>" />
	<meta property="og:type" content="article" />
	<meta property="og:url" content="https://www.nutrii.com.br/" />
	<meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
	<meta property="og:site_name" content="Nova Nutrii" />
<?php endif; ?>

<link type="application/opensearchdescription+xml" rel="search" href="https://www.nutrii.com.br/opensearch.xml">
<link rel="canonical" href="https://www.nutrii.com.br/" />

<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<script src="https://use.typekit.net/drj8mpf.js"></script>
<script>try{Typekit.load({ async: false });}catch(e){}</script>

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->

<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>lib/jquery/jquery-1.12.0.min.js"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>infinite/jquery.ias.min.js"></script>

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) ?>frontend/default/adaptive-shop/css/styles.css?v=11"/>


<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "url": "https://www.nutrii.com.br/",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "https://www.nutrii.com.br/catalogsearch/result/?q={q}",
    "query-input": "name=q"
  }
}
</script>
