<li><a href="/tipos-de-dietas">Dietas</a>
	<ul class="dl-submenu">
		<li><a href="/tipos-de-dietas">Tipos de Dietas</a>
			<ul class="dl-submenu">
				<li><a href="/tipos-de-dietas/dieta-padrao">Dieta Padrão</a></li>
				<li><a href="/tipos-de-dietas/dieta-especializada">Dieta Especializada</a></li>
				<li><a href="/tipos-de-dietas/hipercalorica">Hipercalóricas</a></li>
				<li><a href="/tipos-de-dietas/hiperproteica">Hiperprotéica</a></li>
				<li><a href="/tipos-de-dietas/infantil">Infantil</a></li>
				<li><a href="/suplementos/diabetes-ou-controle-glicemico">Diabetes e Controle Glicêmico</a></li>
				<li><a href="/tipos-de-dietas/dieta-padrao-com-fibras">Dieta padrão com fibras</a></li>
			</ul>
		</li>
		<li><a href="/suplementos">Suplementos</a>
			<ul class="dl-submenu">
				<li><a href="/suplementos/cicatrizacao">Cicatrização</a></li>
				<li><a href="/suplementos/desnutricao-ou-geriatria">Desnutrição</a></li>
				<li><a href="/suplementos/diabetes-ou-controle-glicemico">Diabetes</a></li>
				<li><a href="/suplementos/desnutricao-ou-geriatria">Geriatria</a></li>
				<li><a href="/suplementos/desnutricao-ou-geriatria">Hipercalórico</a></li>
				<li><a href="/suplementos/desnutricao-ou-geriatria">Normocalórico</a></li>
				<li><a href="/suplementos/oncologia">Oncologia</a></li>
				<li><a href="/suplementos/pediatria">Pediatria</a></li>
				<li><a href="/suplementos/pre-e-pos-operatorio-imunidade">Pré e Pós Operatório</a></li>
				<li><a href="/suplementos/situacoes-criticas">Situações Críticas</a></li>
				<li><a href="/suplementos/situacoes-gastrointestinais">Situações Gastro</a></li>
			</ul>
		</li>
		<li><a href="/por-patologia">Patologia</a>
			<ul class="dl-submenu">
				<li><a href="/por-patologia/cancer">Cancer</a></li>
				<li><a href="/por-patologia/cicatrizacao-de-feridas">Cicatrização</a></li>
				<li><a href="/por-patologia/cirurgia-cicatrizacao">Cirugia</a></li>
				<li><a href="/por-patologia/desnutricao">Desnutrição</a></li>
				<li><a href="/por-patologia/diabetes">Diabetes</a></li>
				<li><a href="/por-patologia/disfagia-ou-dificuldade-degluticao">Disfagia</a></li>
				<li><a href="/por-patologia/gastrointestinais">Gastro</a></li>
				<li><a href="/por-patologia/imunidade">Imunidade</a></li>
				<li><a href="/por-patologia/renal">Renal</a></li>
			</ul>
		</li>
	</ul>
</li>
<li><a href="/modulos-nutricionais">Módulos nutricionais</a>
	<ul class="dl-submenu">
		<li><a href="/modulos-nutricionais/espessante">Espessante</a></li>
		<li><a href="/modulos-nutricionais/fibras-ou-prebioticos">Fibras</a></li>
		<li><a href="/modulos-nutricionais/glutamina">Glutamina</a></li>
		<li><a href="/modulos-nutricionais/proteina">Proteína</a></li>
		<li><a href="/modulos-nutricionais/simbiotico">Simbiótico</a></li>
	</ul>
</li>
<li><a href="/vida-saudavel">Vida saudável</a>
	<ul class="dl-submenu">
		<li><a href="/vida-saudavel/suplemento-alimentar/omega-3">Omega 3</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/detox">Detox</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/goji-berry">Goji Berry</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/colageno">Colágeno</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/oleo-de-cartamo">Óleo de Cártamo</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/dualberry">Dualberry</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/thermo-goji">Thermo Goji</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/actlin-1000mg-60caps">Actlin</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/matcha">Matcha</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/cha-verde">Chá Verde</a></li>
		<li><a href="/vida-saudavel/suplemento-alimentar/up-energy">Up Energy</a></li>
	</ul>
</li>
<li><a href="/acessorios">Acessórios</a>
	<ul class="dl-submenu">
		<li><a href="/acessorios/equipos-descartaveis">Equipos</a></li>
		<li><a href="/acessorios/frascos-descartaveis">Frascos</a></li>
		<li><a href="/acessorios/higienizacao">Higienização</a></li>
		<li><a href="/acessorios/seringa">Seringa</a></li>
	</ul>
</li>
<div class="bg-menu"></div>

