<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div id="colunas12" class="m-top">
    <h1 class="cor bold fs-25"><?php echo $this->__('Shopping Cart') ?></h1>
</div>

<div id="colunas12" class="no-bottom">
    <div class="h-r f-l d-b"></div>
</div>

<div id="colunas12">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1" />
                <col />
                <col width="1" />
                <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                    <col width="1" />
                <?php endif ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <col width="1" />
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <col width="1" />

                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                <tr>
                    <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
                    <th rowspan="<?php echo $mergedCells; ?>"><span class="txt fs-14 nobr"><?php echo $this->__('Product Name') ?></span></th>
                    <th rowspan="<?php echo $mergedCells; ?>"><!--<span class="nobr fs-14 nobr">Editar</span>--></th>
                    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr fs-14 nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                    <?php endif ?>
                    <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr fs-14 nobr"><?php echo $this->__('Unit Price') ?></span></th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr fs-14 nobr"><?php echo $this->__('Qty') ?></span></th>
                    <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr fs-14 nobr"><?php echo $this->__('Subtotal') ?></span></th>
                    <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr fs-14 nobr">Remover</span></th>
                </tr>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                <?php endif; ?>
                <br />
                </thead>

                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="50" class="a-right">
                        <br />
                        <?php if($this->getContinueShoppingUrl()): ?>
                            <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button bt3 radius cor-sec fs-11 tt-u bold td-n btn-continue" onclick="setLocation('<?php echo $this->getUrl() //echo $this->getContinueShoppingUrl() ?>')"><?php echo $this->__('Continue Shopping') ?></button>
                        <?php endif; ?>
                        <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button bt3 radius cor-sec fs-11 tt-u bold td-n btn-update"><?php echo $this->__('Update Shopping Cart'); ?></button>
                        <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button bt3 radius cor-sec fs-11 tt-u bold td-n btn-empty" id="empty_cart_button"><?php echo $this->__('Clear Shopping Cart'); ?></button>
                        <!--[if lt IE 8]>
                        <input type="hidden" id="update_cart_action_container" />
                        <script type="text/javascript">
                            //<![CDATA[
                                Event.observe(window, 'load', function()
                                {
                                    // Internet Explorer (lt 8) does not support value attribute in button elements
                                    $emptyCartButton = $('empty_cart_button');
                                    $cartActionContainer = $('update_cart_action_container');
                                    if ($emptyCartButton && $cartActionContainer) {
                                        Event.observe($emptyCartButton, 'click', function()
                                        {
                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                                            $cartActionContainer.setValue('empty_cart');
                                        });
                                    }

                                });
                            //]]>
                            </script>
                            <![endif]-->
                    </td>
                </tr>
                </tfoot>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
</div>

<div id="colunas12">
    <div class="h-r f-l d-b"></div>
</div>

<div id="colunas6">
    <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
</div>
<div id="colunas6">
    <!--<p class="cor f-r fs-25 bold txt-sub">Subtotal: <span class="txt">
	<?php
    $subtotal = Mage::getModel('checkout/cart')->getQuote()->getSubtotal();
    echo Mage::helper('checkout')->formatPrice($subtotal) ?>&nbsp;</span></p>-->
    <?php echo $this->getChildHtml('totals'); ?>
    <button type="button" title="<?php echo $this->__('Checkout') ?>" class="clear f-r bt-buy bt fs-16 d-b cor-sec bold tt-u radius td-n" onclick="setLocation('<?php echo $this->getUrl('onestepcheckout/index/', '_nosid'); ?>')">Continuar</button>
</div>

<div class="h-r f-l d-b"></div>

<!-- Related products block START -->
<div class="related">
    <div class="wrapper-categoria">


        <?php
        $array_added_product = array();
        $total_product= "";
        $last_product= "";
        ?>
        <?php foreach($this->getItems() as $_item):
            $array_added_product[]=$_item->getProductId();?>
        <?php endforeach ?>
        <?php
        $total_product=sizeof($array_added_product);
        if($total_product > 0){
            $last_product=$array_added_product[($total_product-1)];
        }
        ?>
        <?php
        $nProducts = $total_product;
        $_product = Mage::getModel('catalog/product')->load($total_product-1);
        $ids = array();
        while ((count($ids) < 8) && ($nProducts > 0)){
            $nProducts --;
            $last_product=$array_added_product[($nProducts)];
            $_product1 = Mage::getModel('catalog/product')->load($last_product);
            if (!$_product1->hasRelatedProductIds()) {
                foreach ($_product1->getRelatedProducts() as $product) {
                    if (count($ids) < 8) $ids[] = $product->getId();
                    else break;
                }
                $_product->setRelatedProductIds($ids);
            }
        }
        ?>
        <?php $product_per_row=8; //how many product show in a row ?>


        <?php
        $product_counter=0;
        foreach ($_product->getData('related_product_ids') as $r_productid) {
            $_product = Mage::getModel('catalog/product')->load($r_productid);
            ?>
            <?php if(($product_counter%$product_per_row)==0){ ?>
                <div class="product-feature-title page-nutrii" style="width: 100%;text-align: left;margin: 35px 0;display: inline-block;float: left;max-width: 100%;">
                    <h3>Adicione ao carrinho os acessórios recomendados para esse produto</h3>
                </div>

            <?php } ?>
            <div id="colunas3" class="prod">
                <div class="nova-h">
                    <div class="tag-label">
                        <?php if($_product->isSaleable()): ?>
                        <?php else: ?>
                            <p class="novo">esgotado</p>
                        <?php endif; ?>
                        <?php // flag novo produto ?>
                        <?php // Limit dates for newness
                        $newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
                        $newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();
                        // Date and time (now)
                        $now = date("Y-m-d");
                        if($newFromDate < $now && $newToDate >= $now): ?>
                            <p class="kepler-bold-italic novo">novidade</p>
                        <?php endif; ?>
                        <?php // flag promoção ?>
                        <?php
                        // Get the Special Price
                        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
                        // Get the Special Price FROM date
                        $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                        // Get the Special Price TO date
                        $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                        // Get Current date
                        $today =  time();
                        if ($specialprice):
                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >=
                                strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)): ?>
                                <p class="kepler-bold-italic oferta">promo&ccedil;&atilde;o</p>
                            <?php
                            endif;
                        endif;
                        ?>
                    </div>
                    <a href="<?php echo $_product->getProductUrl(); //echo '/?'.$SID; ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <img class="img-prod" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(263); ?>" width="263" height="263" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                    <div id="info-prod">
                        <a class="fs-19 txt d-b bold" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?>"><h2><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></h2></a>
                        <div class="mob">

                            <?php
                            /* Desconto em uma vez no cartão (5% de desconto) */

                            $desconto = 5;
                            $preco =(float) $_product->getPrice();
                            $precoComDesconto = $preco - ($preco * $desconto / 100);

                            $msgDescCartao   = "<p class='msg-desconto-cartao'>";
                            $msgDescCartao  .=     "<span class='medium'>em 1x no cartão de crédito por:</span>";
                            $msgDescCartao  .=     "<span class='display-preco-com-desconto bold'>R$ ".number_format($precoComDesconto, 2, ',', '')."</span>";
                            $msgDescCartao  .= "</p>";

                            echo $msgDescCartao;
                            ?>

                            <?php if(!$_product->isGrouped()): ?>
                            <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($_product)?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                                <div class="list-qtd">
                                    <span class="less">-</span>
                                    <input style="width:22px;float:none;text-align:center;" class="op-i" type="text" name="qty" id="qty" maxlength="5" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" />
                                    <span class="more">+</span>
                                </div>
                                <?php endif; ?>
                                <div class="bt-nova">
                                    <a href="javascript:void(0)" title="Comprar" onclick="document.getElementById('product_addtocart_form_<?php echo $_product->getId()?>').submit(); return false">Comprar</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <?php
            $product_counter++;
            if(($product_counter%$product_per_row)==0){
                ?>
            <?php } ?>
        <?php } ?>
        <script type="text/javascript">
            $j = jQuery.noConflict();

            $j(document).ready(function() {
                $j(".list-qtd span.less").on("click", function() {
                    var qtd_current = parseInt($j(this).parents(".list-qtd").find("input").val());
                    return qtd_current--, 0 >= qtd_current && (qtd_current = 1), qtd_current > 9 || (qtd_current = qtd_current),$j(this).parents(".list-qtd").find("input").val(qtd_current), !1
                });
                $j(".list-qtd span.more").on("click", function() {
                    var qtd_current = parseInt($j(this).parents(".list-qtd").find("input").val());
                    return qtd_current++, qtd_current > 9 || (qtd_current = qtd_current), $j(this).parents(".list-qtd").find("input").val(qtd_current), !1
                });
            })

        </script>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

    </div>
</div>
