<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

$quote = Mage::getSingleton('checkout/session')->getQuote();
$quote->delete();

?>

<?php
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
//$order_details = Mage::getModel('sales/order')->loadByIncrementId($orderId);

Mage::app()->setCurrentStore(Mage_Core_Model_App::ADMIN_STORE_ID);
//$order = Mage::getModel('sales/order')->loadByIncrementId($orderId);
//if($order->getPayment()->getMethod() == "boleto_bancario"): /*caso tenha cido escolhido boleto como meio de pagamento exibe o botão abaixo*/
?>

  <?php
		$order = Mage::getModel ( 'sales/order' );
		$order->loadByIncrementId ( $this->getOrderId () );
		$method = $order->getPayment ()->getMethod ();
		$valortotal = $order->getGrandTotal();
		$valorfrete = $order->getShippingAmount();

?>

<div id="colunas6" class="cart-success1 m-top">
    <p class="fs-20">Pedido realizado <span class="bold">com sucesso!</span></p>
    <p class="txt bold fs-25 obg">Obrigado!</p>
</div>

<div id="colunas6" class="cart-success2 m-top">
    <h2 class="cor bold sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>
    <br />
<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
    <p class="txt fs-16"><?php echo $this->__('Your order # is: %s.', sprintf('<a class="bold" href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>
    <p class="txt fs-16"><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
<?php endif;?>
    <p class="txt fs-16"><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p class="txt fs-16">
        <?php echo $this->__('Clique <a style="color:#0fb400;" href="%s" onclick="this.target=\'_blank\'">aqui</a> para imprimir seu pedido.', $this->getPrintUrl()) ?>
        <?php echo $this->getChildHtml() ?>
    </p>
<?php endif;?>

<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a class="bold" href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>
</div>

<div id="colunas12"></div>

