<?php
/**
 * @see Mage_Payment_Block_Info
 */
?>
<p><?php echo $this->htmlEscape($this->getMethod()->getTitle()); ?></p>

<?php
    $payment_code = $this->getMethod()->getMethodCode();   
?>
<?php if ($_specificInfo = $this->getSpecificInformation()) { ?>
<table>
    <tbody>
    <?php foreach ($_specificInfo as $_label => $_value) { ?>
        <tr>
            <th><?php echo $this->escapeHtml($_label); ?></th>
            <td>
            <?php 
            
            if ($payment_code == 'superpay' && strstr($_label,'Tipo')) {
                $type = $this->getMethod()->getOrderCCType(); 
                $cc_type = $this->getMethod()->getCCType($type); 
                echo $cc_type;
            } else {
                echo nl2br(implode($this->getValueAsArray($_value, true), "\n"));   
            } ?>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php } ?>

<?php echo $this->getChildHtml();?>
