<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Pagarme
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<br />

<div id="colunas12">
	<a href="javascript:void(0);" class="btn-boleto bold txt fs-16 d-b ta-c" title="Clique aqui para imprimir o Boleto" onclick="window.open('<?php echo $this->getBoletoUrl() ?>')"><span>Clique aqui!<img border="0" name="banner" src="<?php echo $this->getSkinUrl('images/botao-boleto2x.jpg'); ?>" width="33" height="40" />Para imprimir o Boleto!</span></a>
</div>
